version: "3.9"
services:
    postgres:
        image: "postgres"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=010203
            - POSTGRES_DB=postgres
        ports:
            - "5435:5432"
        volumes:
            - postgresvol:/var/lib/postgresql/data
            - ./src/db/dump:/docker-entrypoint-initdb.d
volumes:
    postgresvol:
